[package]
name = "repo_cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
git2 = "0.19.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
